import { pipeline, TextStreamer } from "@huggingface/transformers";

// Create a text generation pipeline
const generator = await pipeline(
  "text-generation",
  "onnx-community/Qwen2.5-Coder-0.5B-Instruct",
  { dtype: "q4" },
);


const infos = [
    "The price of 'The Great Gatsby' is $10.99.",
    "The price of '1984' is $8.50.",
    "The price of 'To Kill a Mockingbird' is $12.75.",
    "The price of 'Pride and Prejudice' is $9.00.",
    "The price of 'Moby Dick' is $11.25.",
    "The price of 'The Catcher in the Rye' is $7.99.",
    "The price of 'Lord of the Flies' is $6.50.",
    "The price of 'Animal Farm' is $5.99.",
    "The price of 'Brave New World' is $9.25.",
    "The price of 'The Hobbit' is $12.00.",
    "The price of 'Fahrenheit 451' is $8.75.",
    "The price of 'Jane Eyre' is $10.50.",
    "The price of 'Wuthering Heights' is $9.99.",
    "The price of 'Great Expectations' is $11.00.",
    "The price of 'A Tale of Two Cities' is $10.25.",
    "The price of 'Crime and Punishment' is $13.50.",
    "The price of 'War and Peace' is $15.99.",
    "The price of 'The Brothers Karamazov' is $14.75.",
    "The price of 'Anna Karenina' is $12.99.",
    "The price of 'Don Quixote' is $11.50.",
    "The price of 'Les Misérables' is $14.00.",
    "The price of 'The Count of Monte Cristo' is $13.25.",
    "The price of 'Dracula' is $8.99.",
    "The price of 'Frankenstein' is $7.50.",
    "The price of 'The Picture of Dorian Gray' is $9.75.",
    "The price of 'Heart of Darkness' is $6.25.",
    "The price of 'Things Fall Apart' is $10.00.",
    "The price of 'The Alchemist' is $8.50.",
    "The price of 'Siddhartha' is $7.25.",
    "The price of 'The Stranger' is $9.00.",
    "The price of 'One Hundred Years of Solitude' is $11.99.",
    "The price of 'Love in the Time of Cholera' is $10.75.",
    "The price of 'The Metamorphosis' is $6.99.",
    "The price of 'The Trial' is $8.25.",
    "The price of 'Catch-22' is $12.50.",
    "The price of 'Slaughterhouse-Five' is $9.50.",
    "The price of 'A Clockwork Orange' is $10.25.",
    "The price of 'The Handmaid’s Tale' is $11.00.",
    "The price of 'Dune' is $14.50.",
    "The price of 'Foundation' is $13.00.",
    "The price of 'Ender’s Game' is $9.99.",
    "The price of 'The Hitchhiker’s Guide to the Galaxy' is $8.75.",
    "The price of 'Neuromancer' is $10.50.",
    "The price of 'Snow Crash' is $11.25.",
    "The price of 'Harry Potter and the Sorcerer’s Stone' is $12.99.",
    "The price of 'The Lord of the Rings' is $19.99.",
    "The price of 'Game of Thrones' is $15.50.",
    "The price of 'The Hunger Games' is $10.00.",
    "The price of 'Divergent' is $9.25.",
    "The price of 'The Maze Runner' is $8.50.",
    "The price of 'The Fault in Our Stars' is $11.75.",
    "The price of 'Gone Girl' is $12.25.",
    "The price of 'The Girl with the Dragon Tattoo' is $13.00.",
    "The price of 'The Da Vinci Code' is $9.99.",
    "The price of 'Angels & Demons' is $8.75.",
    "The price of 'Inferno' is $10.50.",
    "The price of 'The Kite Runner' is $11.00.",
    "The price of 'A Thousand Splendid Suns' is $10.25.",
    "The price of 'Life of Pi' is $9.50.",
    "The price of 'The Book Thief' is $12.00.",
    "The price of 'The Help' is $11.50.",
    "The price of 'Water for Elephants' is $10.75.",
    "The price of 'The Secret Life of Bees' is $9.25.",
    "The price of 'Eat Pray Love' is $8.99.",
    "The price of 'Wild' is $10.00.",
    "The price of 'Into the Wild' is $9.75.",
    "The price of 'The Martian' is $11.99.",
    "The price of 'Ready Player One' is $12.50.",
    "The price of 'The Night Circus' is $10.25.",
    "The price of 'The Goldfinch' is $14.00.",
    "The price of 'A Little Life' is $13.75.",
    "The price of 'The Ocean at the End of the Lane' is $9.50.",
    "The price of 'American Gods' is $11.25.",
    "The price of 'Good Omens' is $10.50.",
    "The price of 'Stardust' is $9.00.",
    "The price of 'Coraline' is $8.25.",
    "The price of 'The Graveyard Book' is $7.99.",
    "The price of 'It' is $15.00.",
    "The price of 'The Shining' is $12.75.",
    "The price of 'Misery' is $11.50.",
    "The price of 'Carrie' is $9.75.",
    "The price of 'Pet Sematary' is $10.25.",
    "The price of 'The Stand' is $14.99.",
    "The price of 'Under the Dome' is $13.50.",
    "The price of '11/22/63' is $12.99.",
    "The price of 'The Green Mile' is $11.00.",
    "The price of 'Shawshank Redemption' is $9.50.",
    "The price of 'A Game of Thrones' is $15.25.",
    "The price of 'A Clash of Kings' is $14.75.",
    "The price of 'A Storm of Swords' is $15.00.",
    "The price of 'A Feast for Crows' is $14.25.",
    "The price of 'A Dance with Dragons' is $15.50.",
    "The price of 'The Winds of Winter' is $16.00.",
    "The price of 'The Silmarillion' is $13.25.",
    "The price of 'Unfinished Tales' is $12.50.",
    "The price of 'The Children of Húrin' is $11.75.",
    "The price of 'Beren and Lúthien' is $10.99.",
    "The price of 'The Fall of Gondolin' is $10.50.",
    "The price of 'The Name of the Wind' is $12.25.",
    "The price of 'The Wise Man’s Fear' is $12.75.",
    "The price of 'Mistborn: The Final Empire' is $11.99.",
    "The price of 'The Well of Ascension' is $11.50.",
    "The price of 'The Hero of Ages' is $12.00.",
    "The price of 'The Way of Kings' is $14.50.",
    "The price of 'Words of Radiance' is $14.75.",
    "The price of 'Oathbringer' is $15.00.",
    "The price of 'Rhythm of War' is $15.25.",
    "The price of 'Elantris' is $11.25.",
    "The price of 'Warbreaker' is $10.75.",
    "The price of 'The Emperor’s Soul' is $8.50.",
    "The price of 'Persepolis' is $9.99.",
    "The price of 'Maus' is $12.00.",
    "The price of 'Watchmen' is $14.00.",
    "The price of 'V for Vendetta' is $13.50.",
    "The price of 'Sandman: Preludes & Nocturnes' is $11.99.",
    "The price of 'Saga, Volume 1' is $9.75.",
    "The price of 'Monstress, Volume 1' is $10.25.",
    "The price of 'Paper Girls, Volume 1' is $9.50.",
    "The price of 'Y: The Last Man, Volume 1' is $10.00.",
    "The price of 'Preacher, Volume 1' is $11.00.",
    "The price of 'Fables, Volume 1' is $10.50.",
    "The price of 'Bone: Out from Boneville' is $9.25.",
    "The price of 'Calvin and Hobbes' is $12.99.",
    "The price of 'The Far Side Gallery' is $11.75.",
    "The price of 'Garfield at Large' is $8.99.",
    "The price of 'Dilbert Principle' is $9.50.",
    "The price of 'Pride and Prejudice and Zombies' is $10.25.",
    "The price of 'Sense and Sensibility and Sea Monsters' is $9.75.",
    "The price of 'World War Z' is $11.50.",
    "The price of 'The Zombie Survival Guide' is $10.00.",
    "The price of 'I Am Legend' is $9.25.",
    "The price of 'The Road' is $10.75.",
    "The price of 'Station Eleven' is $11.25.",
    "The price of 'The Passage' is $12.50.",
    "The price of 'The Girl Who Owned a City' is $8.50.",
    "The price of 'The Dog Stars' is $9.99.",
    "The price of 'A Canticle for Leibowitz' is $10.50.",
    "The price of 'Alas, Babylon' is $9.75.",
    "The price of 'On the Beach' is $10.00.",
    "The price of 'The Postman' is $11.00.",
    "The price of 'Earth Abides' is $10.25.",
    "The price of 'The Day of the Triffids' is $9.50.",
  ];


// Combine infos into a single context string
const context = infos.join(" ");

// Define the messages for the LLM
const messages = [
  { role: "system", content: "You are a helpful assistant." },
  { 
    role: "user", 
    content: `Context: ${context}\nQuestion: What is the price of '1984'?` 
  },
];

// Create text streamer
const streamer = new TextStreamer(generator.tokenizer, {
  skip_prompt: true,

})

// Generate a response
const result = await generator(messages, { max_new_tokens: 512, do_sample: false, streamer });